# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "2fb1ed56-563d-40a6-8e81-ce5a442cb8a0",
# META       "default_lakehouse_name": "LH_Sales",
# META       "default_lakehouse_workspace_id": "4dcb26f9-27e5-4575-8d90-e3103a1bd6c1",
# META       "known_lakehouses": [
# META         {
# META           "id": "2fb1ed56-563d-40a6-8e81-ce5a442cb8a0"
# META         }
# META       ]
# META     }
# META   }
# META }

# MARKDOWN ********************

# ### List all products ###

# CELL ********************

df = spark.sql("SELECT * FROM LH_Sales.products LIMIT 1000")
display(df)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for PySpark DataFrame

def clean_data(df):
    # Rename column 'Price' to 'ListPrice'
    df = df.withColumnRenamed('Price', 'ListPrice')
    return df

df_clean = clean_data(df)
display(df_clean)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
