CREATE TABLE [dbo].[ProductDescriptions] (

	[PRODUCTID] varchar(10) NOT NULL, 
	[PRODUCT_MEDIUM_DESCRIPTION_EN] varchar(1024) NULL, 
	[PRODUCT_MEDIUM_DESCRIPTION_DE] varchar(1024) NULL, 
	[PRODUCT_MEDIUM_DESCRIPTION_FR] varchar(1024) NULL, 
	[PRODUCT_MEDIUM_DESCRIPTION_ES] varchar(1024) NULL, 
	[PRODUCT_LONG_DESCRIPTION_EN] varchar(4000) NULL, 
	[PRODUCT_LONG_DESCRIPTION_DE] varchar(4000) NULL, 
	[PRODUCT_LONG_DESCRIPTION_FR] varchar(4000) NULL, 
	[PRODUCT_LONG_DESCRIPTION_ES] varchar(4000) NULL
);