CREATE TABLE [dbo].[ProductCategoryDescriptions] (

	[PRODCATEGORYID] varchar(2) NOT NULL, 
	[PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_EN] varchar(1024) NULL, 
	[PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_DE] varchar(1024) NULL, 
	[PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_FR] varchar(1024) NULL, 
	[PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_ES] varchar(1024) NULL, 
	[PRODUCT_CATEGORY_LONG_DESCRIPTION_EN] varchar(4000) NULL, 
	[PRODUCT_CATEGORY_LONG_DESCRIPTION_DE] varchar(4000) NULL, 
	[PRODUCT_CATEGORY_LONG_DESCRIPTION_FR] varchar(4000) NULL, 
	[PRODUCT_CATEGORY_LONG_DESCRIPTION_ES] varchar(4000) NULL
);