CREATE TABLE [dbo].[ProductCategoryNames] (

	[PRODCATEGORYID] varchar(2) NOT NULL, 
	[PRODUCT_CATEGORY_NAME_EN] varchar(256) NULL, 
	[PRODUCT_CATEGORY_NAME_DE] varchar(256) NULL, 
	[PRODUCT_CATEGORY_NAME_FR] varchar(256) NULL, 
	[PRODUCT_CATEGORY_NAME_ES] varchar(256) NULL
);