DROP TABLE IF EXISTS [CustomerAddresses]
CREATE TABLE CustomerAddresses (
	[ADDRESSID] int NOT NULL,
	[CITY] varchar(80),
	[POSTALCODE] varchar(10),
	[STREET] varchar(80),
	[BUILDING] int,
	[COUNTRY] varchar(256),
	[REGION] varchar(256),
	[ADDRESSTYPE] int,
	[VALIDITY_STARTDATE] date,
	[VALIDITY_ENDDATE] date,
	[LATITUDE] float,
	[LONGITUDE] float)
GO

DROP TABLE IF EXISTS [VendorAddresses]
CREATE TABLE VendorAddresses (
	[ADDRESSID] int NOT NULL,
	[CITY] varchar(80),
	[POSTALCODE] varchar(10),
	[STREET] varchar(80),
	[BUILDING] int,
	[COUNTRY] varchar(256),
	[REGION] varchar(256),
	[ADDRESSTYPE] int,
	[VALIDITY_STARTDATE] date,
	[VALIDITY_ENDDATE] date,
	[LATITUDE] float,
	[LONGITUDE] float)
GO

DROP TABLE IF EXISTS [EmployeeAddresses]
CREATE TABLE EmployeeAddresses (
	[ADDRESSID] int NOT NULL,
	[CITY] varchar(80),
	[POSTALCODE] varchar(10),
	[STREET] varchar(80),
	[BUILDING] int,
	[COUNTRY] varchar(256),
	[REGION] varchar(256),
	[ADDRESSTYPE] int,
	[VALIDITY_STARTDATE] date,
	[VALIDITY_ENDDATE] date,
	[LATITUDE] float,
	[LONGITUDE] float)
GO

DROP TABLE IF EXISTS [Customers]
CREATE TABLE Customers (
	[CUSTOMERID] int NOT NULL,
	[EMAILADDRESS] varchar(1024),
	[PHONENUMBER] varchar(20),
	[FAXNUMBER] varchar(20),
	[WEBADDRESS] varchar(1024),
	[ADDRESSID] int,
	[COMPANYNAME] varchar(256),
	[LEGALFORM] varchar(1024),
	[CREATEDBY] int,
	[CREATEDAT] date,
	[CHANGEDBY] int,
	[CHANGEDAT] date,
	[CURRENCY] varchar(3))
GO

DROP TABLE IF EXISTS [Vendors]
CREATE TABLE Vendors (
	[VENDORID] int NOT NULL,
	[EMAILADDRESS] varchar(1024),
	[PHONENUMBER] varchar(20),
	[FAXNUMBER] varchar(20),
	[WEBADDRESS] varchar(1024),
	[ADDRESSID] int,
	[COMPANYNAME] varchar(256),
	[LEGALFORM] varchar(1024),
	[CREATEDBY] int,
	[CREATEDAT] date,
	[CHANGEDBY] int,
	[CHANGEDAT] date,
	[CURRENCY] varchar(3))
GO

DROP TABLE IF EXISTS [Employees]
CREATE TABLE Employees (
	[EMPLOYEEID] int NOT NULL,
	[NAME_FIRST] varchar(80),
	[NAME_MIDDLE] varchar(80),
	[NAME_LAST] varchar(80),
	[NAME_INITIALS] varchar(10),
	[SEX] varchar(10),
	[LANGUAGE] varchar(5),
	[PHONENUMBER] varchar(20),
	[EMAILADDRESS] varchar(1024),
	[LOGINNAME] varchar(80),
	[ADDRESSID] int,
	[VALIDITY_STARTDATE] date,
	[VALIDITY_ENDDATE] date)
GO

DROP TABLE IF EXISTS [ProductCategories]
CREATE TABLE ProductCategories (
	[PRODCATEGORYID] varchar(2) NOT NULL,
	[CREATEDBY] int,
	[CREATEDAT] date)
GO

DROP TABLE IF EXISTS [ProductCategoryTexts]
CREATE TABLE ProductCategoryTexts (
	[PRODCATEGORYID] varchar(2) NOT NULL,
	[LANGUAGE] varchar(5) NOT NULL,
	[SHORT_DESCR] varchar(256),
	[MEDIUM_DESCR] varchar(1024),
	[LONG_DESCR] varchar(4000))
GO

DROP TABLE IF EXISTS [ProductCategoryNames]
CREATE TABLE ProductCategoryNames (
    [PRODCATEGORYID] varchar(2) NOT NULL,
    [PRODUCT_CATEGORY_NAME_EN] varchar(256),
    [PRODUCT_CATEGORY_NAME_DE] varchar(256),
    [PRODUCT_CATEGORY_NAME_FR] varchar(256),
    [PRODUCT_CATEGORY_NAME_ES] varchar(256))
GO

DROP TABLE IF EXISTS [ProductCategoryDescriptions]
CREATE TABLE ProductCategoryDescriptions (
    [PRODCATEGORYID] varchar(2) NOT NULL,
    [PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_EN] varchar(1024),
    [PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_DE] varchar(1024),
    [PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_FR] varchar(1024),
    [PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_ES] varchar(1024),
    [PRODUCT_CATEGORY_LONG_DESCRIPTION_EN] varchar(4000),
    [PRODUCT_CATEGORY_LONG_DESCRIPTION_DE] varchar(4000),
    [PRODUCT_CATEGORY_LONG_DESCRIPTION_FR] varchar(4000),
    [PRODUCT_CATEGORY_LONG_DESCRIPTION_ES] varchar(4000))
GO

DROP TABLE IF EXISTS [Products]
CREATE TABLE Products (
	[PRODUCTID] varchar(10) NOT NULL,
	[TYPECODE] varchar(2),
	[PRODCATEGORYID] varchar(2) NOT NULL,
	[CREATEDBY] int,
	[CREATEDAT] date,
	[CHANGEDBY] int,
	[CHANGEDAT] date,
	[VENDORID] int,
	[TAXTARIFFCODE] int,
	[QUANTITYUNIT] varchar(10),
	[WEIGHTMEASURE] decimal(10,4),
	[WEIGHTUNIT] varchar(10),
	[CURRENCY] varchar(3),
	[PRICE] decimal(10,2),
	[WIDTH]decimal(10,4),
	[DEPTH] decimal(10,4),
	[HEIGHT] decimal(10,4),
	[DIMENSIONUNIT] varchar(80),
	[PRODUCTPICURL] varchar(1024))
GO

DROP TABLE IF EXISTS [ProductTexts]
CREATE TABLE ProductTexts (
	[PRODUCTID] varchar(10) NOT NULL,
	[LANGUAGE] varchar(5) NOT NULL,
	[SHORT_DESCR] varchar(256),
	[MEDIUM_DESCR] varchar(1024),
	[LONG_DESCR] varchar(4000))
GO

DROP TABLE IF EXISTS [ProductNames]
CREATE TABLE ProductNames (
	[PRODUCTID] varchar(10) NOT NULL,
	[PRODUCT_NAME_EN] varchar(256),
	[PRODUCT_NAME_DE] varchar(256),
	[PRODUCT_NAME_FR] varchar(256),
	[PRODUCT_NAME_ES] varchar(256))
GO

DROP TABLE IF EXISTS [ProductDescriptions]
CREATE TABLE ProductDescriptions (
	[PRODUCTID] varchar(10) NOT NULL,
    [PRODUCT_MEDIUM_DESCRIPTION_EN] varchar(1024),
    [PRODUCT_MEDIUM_DESCRIPTION_DE] varchar(1024),
    [PRODUCT_MEDIUM_DESCRIPTION_FR] varchar(1024),
    [PRODUCT_MEDIUM_DESCRIPTION_ES] varchar(1024),
    [PRODUCT_LONG_DESCRIPTION_EN] varchar(4000),
    [PRODUCT_LONG_DESCRIPTION_DE] varchar(4000),
    [PRODUCT_LONG_DESCRIPTION_FR] varchar(4000),
    [PRODUCT_LONG_DESCRIPTION_ES] varchar(4000))
GO

DROP TABLE IF EXISTS [SalesOrderItems]
CREATE TABLE SalesOrderItems (
	[SALESORDERID] int NOT NULL,
	[SALESORDERITEM] int NOT NULL,
	[PRODUCTID] varchar(10) NOT NULL,
	[NOTEID] varchar(10),
	[CURRENCY] varchar(3),
	[GROSSAMOUNT] decimal(10,4),
	[NETAMOUNT] decimal(10,4),
	[TAXAMOUNT] decimal(10,4),
	[ITEMATPSTATUS] varchar(10),
	[OPITEMPOS] varchar(10),
	[QUANTITY] int,
	[QUANTITYUNIT] varchar(10),
	[DELIVERYDATE] date)
GO

DROP TABLE IF EXISTS [SalesOrders]
CREATE TABLE SalesOrders (
	[SALESORDERID] int NOT NULL,
	[CREATEDBY] int,
	[CREATEDAT] date,
	[CHANGEDBY] int,
	[CHANGEDAT] date,
	[FISCVARIANT] varchar(10),
	[FISCALYEARPERIOD] int,
	[NOTEID] varchar(10),
	[CUSTOMERID] int NOT NULL,
	[SALESORG] varchar(10),
	[CURRENCY] varchar(3),
	[GROSSAMOUNT] decimal(10,4),
	[NETAMOUNT] decimal(10,4),
	[TAXAMOUNT] decimal(10,4),
	[LIFECYCLESTATUS] varchar(10),
	[BILLINGSTATUS] varchar(10),
	[DELIVERYSTATUS] varchar(10))
GO

COPY INTO Employees([EMPLOYEEID], [NAME_FIRST], [NAME_MIDDLE], [NAME_LAST], [NAME_INITIALS], [SEX], [LANGUAGE], [PHONENUMBER], [EMAILADDRESS], [LOGINNAME], [ADDRESSID], [VALIDITY_STARTDATE], [VALIDITY_ENDDATE])
FROM 'https://martinabrledemodata.blob.core.windows.net/bike-sales-data/Employees.csv'
WITH (FILE_TYPE = 'CSV', FIRSTROW = 2);

COPY INTO Customers([CUSTOMERID], [EMAILADDRESS], [PHONENUMBER], [FAXNUMBER], [WEBADDRESS], [ADDRESSID], [COMPANYNAME], [LEGALFORM], [CREATEDBY], [CREATEDAT], [CHANGEDBY], [CHANGEDAT], [CURRENCY])
FROM 'https://martinabrledemodata.blob.core.windows.net/bike-sales-data/Customers.csv'
WITH (FILE_TYPE = 'CSV', FIRSTROW = 2);

COPY INTO Vendors([VENDORID], [EMAILADDRESS], [PHONENUMBER], [FAXNUMBER], [WEBADDRESS], [ADDRESSID], [COMPANYNAME], [LEGALFORM], [CREATEDBY], [CREATEDAT], [CHANGEDBY], [CHANGEDAT], [CURRENCY])
FROM 'https://martinabrledemodata.blob.core.windows.net/bike-sales-data/Vendors.csv'
WITH (FILE_TYPE = 'CSV', FIRSTROW = 2);

INSERT INTO dbo.EmployeeAddresses ([ADDRESSID], [CITY], [POSTALCODE], [STREET], [BUILDING], [COUNTRY], [REGION], [ADDRESSTYPE], [VALIDITY_STARTDATE], [VALIDITY_ENDDATE], [LATITUDE], [LONGITUDE])
SELECT [ADDRESSID], [CITY], [POSTALCODE], [STREET], [BUILDING], [COUNTRY], [REGION], [ADDRESSTYPE], [VALIDITY_STARTDATE], [VALIDITY_ENDDATE], [LATITUDE], [LONGITUDE]
FROM OPENROWSET (
  	BULK 'https://martinabrledemodata.blob.core.windows.net/bike-sales-data/Addresses.csv',
	FORMAT = 'CSV',
	FIELDTERMINATOR = ',',
	HEADER_ROW = TRUE)
WITH (
	[ADDRESSID] int,
	[CITY] varchar(80),
	[POSTALCODE] varchar(10),
	[STREET] varchar(80),
	[BUILDING] int,
	[COUNTRY] varchar(256),
	[REGION] varchar(256),
	[ADDRESSTYPE] int,
	[VALIDITY_STARTDATE] date,
	[VALIDITY_ENDDATE] date,
	[LATITUDE] float,
	[LONGITUDE] float)
AS data
WHERE EXISTS (SELECT 1 FROM Employees A WHERE A.ADDRESSID = data.ADDRESSID);

INSERT INTO dbo.CustomerAddresses ([ADDRESSID], [CITY], [POSTALCODE], [STREET], [BUILDING], [COUNTRY], [REGION], [ADDRESSTYPE], [VALIDITY_STARTDATE], [VALIDITY_ENDDATE], [LATITUDE], [LONGITUDE])
SELECT [ADDRESSID], [CITY], [POSTALCODE], [STREET], [BUILDING], [COUNTRY], [REGION], [ADDRESSTYPE], [VALIDITY_STARTDATE], [VALIDITY_ENDDATE], [LATITUDE], [LONGITUDE]
FROM OPENROWSET (
  	BULK 'https://martinabrledemodata.blob.core.windows.net/bike-sales-data/Addresses.csv',
	FORMAT = 'CSV',
	FIELDTERMINATOR = ',',
	HEADER_ROW = TRUE)
WITH (
	[ADDRESSID] int,
	[CITY] varchar(80),
	[POSTALCODE] varchar(10),
	[STREET] varchar(80),
	[BUILDING] int,
	[COUNTRY] varchar(256),
	[REGION] varchar(256),
	[ADDRESSTYPE] int,
	[VALIDITY_STARTDATE] date,
	[VALIDITY_ENDDATE] date,
	[LATITUDE] float,
	[LONGITUDE] float)
AS data
WHERE EXISTS (SELECT 1 FROM Customers A WHERE A.ADDRESSID = data.ADDRESSID);

INSERT INTO dbo.VendorAddresses ([ADDRESSID], [CITY], [POSTALCODE], [STREET], [BUILDING], [COUNTRY], [REGION], [ADDRESSTYPE], [VALIDITY_STARTDATE], [VALIDITY_ENDDATE], [LATITUDE], [LONGITUDE])
SELECT [ADDRESSID], [CITY], [POSTALCODE], [STREET], [BUILDING], [COUNTRY], [REGION], [ADDRESSTYPE], [VALIDITY_STARTDATE], [VALIDITY_ENDDATE], [LATITUDE], [LONGITUDE]
FROM OPENROWSET (
  	BULK 'https://martinabrledemodata.blob.core.windows.net/bike-sales-data/Addresses.csv',
	FORMAT = 'CSV',
	FIELDTERMINATOR = ',',
	HEADER_ROW = TRUE)
WITH (
	[ADDRESSID] int,
	[CITY] varchar(80),
	[POSTALCODE] varchar(10),
	[STREET] varchar(80),
	[BUILDING] int,
	[COUNTRY] varchar(256),
	[REGION] varchar(256),
	[ADDRESSTYPE] int,
	[VALIDITY_STARTDATE] date,
	[VALIDITY_ENDDATE] date,
	[LATITUDE] float,
	[LONGITUDE] float)
AS data
WHERE EXISTS (SELECT 1 FROM Vendors A WHERE A.ADDRESSID = data.ADDRESSID);

COPY INTO ProductCategories([PRODCATEGORYID],[CREATEDBY], [CREATEDAT])
FROM 'https://martinabrledemodata.blob.core.windows.net/bike-sales-data/ProductCategories.csv'
WITH (FILE_TYPE = 'CSV', FIRSTROW = 2);

COPY INTO ProductCategoryTexts([PRODCATEGORYID], [LANGUAGE], [SHORT_DESCR], [MEDIUM_DESCR], [LONG_DESCR])
FROM 'https://martinabrledemodata.blob.core.windows.net/bike-sales-data/ProductCategoryTexts.csv'
WITH (FILE_TYPE = 'CSV', FIRSTROW = 2);

INSERT INTO ProductCategoryNames ([PRODCATEGORYID], [PRODUCT_CATEGORY_NAME_EN], [PRODUCT_CATEGORY_NAME_DE], [PRODUCT_CATEGORY_NAME_FR], [PRODUCT_CATEGORY_NAME_ES])
SELECT
	[PRODCATEGORYID],
    MAX(CASE WHEN [LANGUAGE] = 'EN' THEN [SHORT_DESCR] END) AS [PRODUCT_CATEGORY_NAME_EN],
    MAX(CASE WHEN [LANGUAGE] = 'DE' THEN [SHORT_DESCR] END) AS [PRODUCT_CATEGORY_NAME_DE],
    MAX(CASE WHEN [LANGUAGE] = 'FR' THEN [SHORT_DESCR] END) AS [PRODUCT_CATEGORY_NAME_FR],
    MAX(CASE WHEN [LANGUAGE] = 'ES' THEN [SHORT_DESCR] END) AS [PRODUCT_CATEGORY_NAME_ES]
FROM ProductCategoryTexts
WHERE [LANGUAGE] IN ('EN', 'DE', 'FR', 'ES')
GROUP BY [PRODCATEGORYID];

INSERT INTO ProductCategoryDescriptions ([PRODCATEGORYID], [PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_EN], [PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_DE], [PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_FR], [PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_ES], [PRODUCT_CATEGORY_LONG_DESCRIPTION_EN], [PRODUCT_CATEGORY_LONG_DESCRIPTION_DE], [PRODUCT_CATEGORY_LONG_DESCRIPTION_FR], [PRODUCT_CATEGORY_LONG_DESCRIPTION_ES])
SELECT
	[PRODCATEGORYID],
    MAX(CASE WHEN [LANGUAGE] = 'EN' THEN [MEDIUM_DESCR] END) AS [PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_EN],
    MAX(CASE WHEN [LANGUAGE] = 'DE' THEN [MEDIUM_DESCR] END) AS [PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_DE],
    MAX(CASE WHEN [LANGUAGE] = 'FR' THEN [MEDIUM_DESCR] END) AS [PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_FR],
    MAX(CASE WHEN [LANGUAGE] = 'ES' THEN [MEDIUM_DESCR] END) AS [PRODUCT_CATEGORY_MEDIUM_DESCRIPTION_ES],
    MAX(CASE WHEN [LANGUAGE] = 'EN' THEN [LONG_DESCR] END) AS [PRODUCT_CATEGORY_LONG_DESCRIPTION_EN],
    MAX(CASE WHEN [LANGUAGE] = 'DE' THEN [LONG_DESCR] END) AS [PRODUCT_CATEGORY_LONG_DESCRIPTION_DE],
    MAX(CASE WHEN [LANGUAGE] = 'FR' THEN [LONG_DESCR] END) AS [PRODUCT_CATEGORY_LONG_DESCRIPTION_FR],
    MAX(CASE WHEN [LANGUAGE] = 'ES' THEN [LONG_DESCR] END) AS [PRODUCT_CATEGORY_LONG_DESCRIPTION_ES]
FROM ProductCategoryTexts
WHERE [LANGUAGE] IN ('EN', 'DE', 'FR', 'ES')
GROUP BY [PRODCATEGORYID];

COPY INTO Products([PRODUCTID],[TYPECODE], [PRODCATEGORYID], [CREATEDBY], [CREATEDAT], [CHANGEDBY], [CHANGEDAT], [VENDORID], [TAXTARIFFCODE], [QUANTITYUNIT], [WEIGHTMEASURE], [WEIGHTUNIT], [CURRENCY], [PRICE], [WIDTH], [DEPTH], [HEIGHT], [DIMENSIONUNIT], [PRODUCTPICURL])
FROM 'https://martinabrledemodata.blob.core.windows.net/bike-sales-data/Products.csv'
WITH (FILE_TYPE = 'CSV', FIRSTROW = 2);

COPY INTO ProductTexts([PRODUCTID], [LANGUAGE], [SHORT_DESCR], [MEDIUM_DESCR], [LONG_DESCR])
FROM 'https://martinabrledemodata.blob.core.windows.net/bike-sales-data/ProductTexts.csv'
WITH (FILE_TYPE = 'CSV', FIRSTROW = 2);

INSERT INTO ProductNames ([PRODUCTID], [PRODUCT_NAME_EN], [PRODUCT_NAME_DE], [PRODUCT_NAME_FR], [PRODUCT_NAME_ES])
SELECT
	[PRODUCTID],
    MAX(CASE WHEN [LANGUAGE] = 'EN' THEN [SHORT_DESCR] END) AS [PRODUCT_NAME_EN],
    MAX(CASE WHEN [LANGUAGE] = 'DE' THEN [SHORT_DESCR] END) AS [PRODUCT_NAME_DE],
    MAX(CASE WHEN [LANGUAGE] = 'FR' THEN [SHORT_DESCR] END) AS [PRODUCT_NAME_FR],
    MAX(CASE WHEN [LANGUAGE] = 'ES' THEN [SHORT_DESCR] END) AS [PRODUCT_NAME_ES]
FROM ProductTexts
WHERE [LANGUAGE] IN ('EN', 'DE', 'FR', 'ES')
GROUP BY [PRODUCTID];

INSERT INTO ProductDescriptions ([PRODUCTID], [PRODUCT_MEDIUM_DESCRIPTION_EN], [PRODUCT_MEDIUM_DESCRIPTION_DE], [PRODUCT_MEDIUM_DESCRIPTION_FR], [PRODUCT_MEDIUM_DESCRIPTION_ES], [PRODUCT_LONG_DESCRIPTION_EN], [PRODUCT_LONG_DESCRIPTION_DE], [PRODUCT_LONG_DESCRIPTION_FR], [PRODUCT_LONG_DESCRIPTION_ES])
SELECT
	[PRODUCTID],
    MAX(CASE WHEN [LANGUAGE] = 'EN' THEN [MEDIUM_DESCR] END) AS [PRODUCT_MEDIUM_DESCRIPTION_EN],
    MAX(CASE WHEN [LANGUAGE] = 'DE' THEN [MEDIUM_DESCR] END) AS [PRODUCT_MEDIUM_DESCRIPTION_DE],
    MAX(CASE WHEN [LANGUAGE] = 'FR' THEN [MEDIUM_DESCR] END) AS [PRODUCT_MEDIUM_DESCRIPTION_FR],
    MAX(CASE WHEN [LANGUAGE] = 'ES' THEN [MEDIUM_DESCR] END) AS [PRODUCT_MEDIUM_DESCRIPTION_ES],
    MAX(CASE WHEN [LANGUAGE] = 'EN' THEN [LONG_DESCR] END) AS [PRODUCT_LONG_DESCRIPTION_EN],
    MAX(CASE WHEN [LANGUAGE] = 'DE' THEN [LONG_DESCR] END) AS [PRODUCT_LONG_DESCRIPTION_DE],
    MAX(CASE WHEN [LANGUAGE] = 'FR' THEN [LONG_DESCR] END) AS [PRODUCT_LONG_DESCRIPTION_FR],
    MAX(CASE WHEN [LANGUAGE] = 'ES' THEN [LONG_DESCR] END) AS [PRODUCT_LONG_DESCRIPTION_ES]
FROM ProductTexts
WHERE [LANGUAGE] IN ('EN', 'DE', 'FR', 'ES')
GROUP BY [PRODUCTID];

COPY INTO SalesOrders([SALESORDERID], [CREATEDBY], [CREATEDAT], [CHANGEDBY], [CHANGEDAT], [FISCVARIANT], [FISCALYEARPERIOD], [NOTEID], [CUSTOMERID], [SALESORG], [CURRENCY], [GROSSAMOUNT], [NETAMOUNT], [TAXAMOUNT], [LIFECYCLESTATUS], [BILLINGSTATUS], [DELIVERYSTATUS])
FROM 'https://martinabrledemodata.blob.core.windows.net/bike-sales-data/SalesOrders.csv'
WITH (FILE_TYPE = 'CSV', FIRSTROW = 2);

COPY INTO SalesOrderItems([SALESORDERID], [SALESORDERITEM], [PRODUCTID], [NOTEID], [CURRENCY], [GROSSAMOUNT], [NETAMOUNT], [TAXAMOUNT], [ITEMATPSTATUS], [OPITEMPOS], [QUANTITY], [QUANTITYUNIT], [DELIVERYDATE])
FROM 'https://martinabrledemodata.blob.core.windows.net/bike-sales-data/SalesOrderItems.csv'
WITH (FILE_TYPE = 'CSV', FIRSTROW = 2);

DROP TABLE IF EXISTS [ProductCategoryTexts];
DROP TABLE IF EXISTS [ProductTexts];